// ====== Relevant Constants
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const CATEGORY_CLICK = 'CATEGORY_CLICK';
export const CATEGORY_WITH_SUBS_CLICK = 'CATEGORY_WITH_SUBS_CLICK';
export const SUB_CATEGORY_CLICK = 'SUB_CATEGORY_CLICK';
export const RESET_CATEGORIES_AND_PATH = 'RESET_CATEGORIES_AND_PATH';
